version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      # - DB:/var/lib/postgresql/data
      - /home/malvern/www/Quiero_regresar_a_casa/database/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123PoStGrEs!

volumes:
  DB:
